name: materia_optima
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.0.3+1
  just_audio: ^0.9.20
  just_audio_libwinmedia: ^0.0.4
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  transparent_image: ^2.0.0
  tuple: ^2.0.0
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ui/
    - assets/element_icons/
    - assets/element_tiles/
    - assets/patterns/
    - assets/ui/inventory_element/
    - assets/ui/compendium_tab/
    - assets/sound_effects/

  fonts:
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
          weight: 700    

flutter_icons:
  android: "launcher_icon"
  web: false
  windows: true
  image_path: "assets/icons/launcher_icon.png"

flutter_native_splash:
  color: "#121212"
  image: assets/icons/aether_icon.png
  web: false

